name: GuiShop
main: GuiShop\Main
version: 1.0.0-BETA1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: VMPE Developement Team 
authors: VMPE Developement TEAM , StCraftPEV3
description: ShopUI for servers!
commands:
 shop:
  description: Opens The StCraftPE ShopGUI
